
package com.fonowizja.client;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "NextWorkingDayProviderServiceImplService", targetNamespace = "http://api.fonowizja.com/", wsdlLocation = "file:/C:/Users/Krzysztof_Kramarz/Desktop/repo/ws-service/ctf.wsdl")
public class NextWorkingDayProviderServiceImplService
        extends Service {

    private final static URL NEXTWORKINGDAYPROVIDERSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException NEXTWORKINGDAYPROVIDERSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName NEXTWORKINGDAYPROVIDERSERVICEIMPLSERVICE_QNAME = new QName("http://api.fonowizja.com/", "NextWorkingDayProviderServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Krzysztof_Kramarz/Desktop/repo/ws-service/ctf.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NEXTWORKINGDAYPROVIDERSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        NEXTWORKINGDAYPROVIDERSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public NextWorkingDayProviderServiceImplService() {
        super(__getWsdlLocation(), NEXTWORKINGDAYPROVIDERSERVICEIMPLSERVICE_QNAME);
    }

    public NextWorkingDayProviderServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NEXTWORKINGDAYPROVIDERSERVICEIMPLSERVICE_QNAME, features);
    }

    public NextWorkingDayProviderServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, NEXTWORKINGDAYPROVIDERSERVICEIMPLSERVICE_QNAME);
    }

    public NextWorkingDayProviderServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NEXTWORKINGDAYPROVIDERSERVICEIMPLSERVICE_QNAME, features);
    }

    public NextWorkingDayProviderServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NextWorkingDayProviderServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns NextWorkingDayProviderService
     */
    @WebEndpoint(name = "NextWorkingDayProviderServiceImplPort")
    public NextWorkingDayProviderService getNextWorkingDayProviderServiceImplPort() {
        return super.getPort(new QName("http://api.fonowizja.com/", "NextWorkingDayProviderServiceImplPort"), NextWorkingDayProviderService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns NextWorkingDayProviderService
     */
    @WebEndpoint(name = "NextWorkingDayProviderServiceImplPort")
    public NextWorkingDayProviderService getNextWorkingDayProviderServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://api.fonowizja.com/", "NextWorkingDayProviderServiceImplPort"), NextWorkingDayProviderService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NEXTWORKINGDAYPROVIDERSERVICEIMPLSERVICE_EXCEPTION != null) {
            throw NEXTWORKINGDAYPROVIDERSERVICEIMPLSERVICE_EXCEPTION;
        }
        return NEXTWORKINGDAYPROVIDERSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
